classdef drEEMstatus
% Copyright (C) 2025 Urban J. Wuensch - wuensch@chalmers.se
% Chalmers University of Technology
% Department of Architecture and Civil Engineering
% Sven Hultins Gata 6
% 41296 Gothenburg (Sweden)
    properties (GetAccess = public,SetAccess = protected)
        spectralCorrection ...
            {mustBeText,...
            mustBeMember(spectralCorrection,...
            ["unknown","not applied","applied by instrument software","applied by toolbox"])} = "unknown"
        IFEcorrection ...
            {mustBeText,...
            mustBeMember(IFEcorrection,...
            ["unknown","not applied","applied by instrument software","applied by toolbox",...
            "deemed unnecessary"])} = "unknown"
        blankSubtraction ...
        {mustBeText,...
            mustBeMember(blankSubtraction,...
            ["unknown","not applied","applied by instrument software","applied by toolbox"])} = "unknown"
        signalCalibration ...
        {mustBeText,...
            mustBeMember(signalCalibration,...
            ["unknown","not applied","applied by instrument software (QSU)",...
             "applied by instrument software (RU)",...
             "applied by toolbox (RU)","applied by toolbox (QSU)"])} = "unknown"
        scatterTreatment ...
        {mustBeText,...
            mustBeMember(scatterTreatment,...
            ["unknown","not applied","applied by instrument software","applied by toolbox"])} = "unknown"
        signalScaling ...
             = "unknown"
        absorbanceUnit ...
            {mustBeText,...
            mustBeMember(absorbanceUnit,...
            ["unknown","absorbance per cm","absorbance per 5 cm","absorbance per 10 cm","napierian absorption coefficient","linear decadic absorption coefficient"])} = "unknown"
    end

    methods (Static=true)
        
        function obj = change(obj,prop,value)
            arguments
                obj {mustBeA(obj,"drEEMstatus")}
                prop ...
                    {mustBeMember(prop,...
                    ["spectralCorrection","IFEcorrection","blankSubtraction",...
                    "signalCalibration","scatterTreatment","signalScaling","absorbanceUnit"])}
                value {mustBeText}
            end

            obj.(prop)=value;

        end

        function [result,message] = isequal(a,b)
            arguments
                a (1,1) {mustBeA(a,'drEEMstatus')}
                b (1,1) {mustBeA(b,'drEEMstatus')}
            end
            cnt=0;
            props=fieldnames(a);
            message='';
            for j=1:numel(props)
                if not(matches(a.(props{j}),b.(props{j})))
                    if cnt==0
                        message=[message,'The drEEMdataset status''es are <strong>not identical</strong>. See below for details:\n'];
                    end
                    cnt=cnt+1;
                    message=[message,'   <strong>',props{j},'</strong>: "',char(a.(props{j})),'" vs. "',char(b.(props{j})),'"\n'];
                end
            end

            if cnt==0
                message='success';
                result=true;
            else
                result=false;
            end

        end
    end
end