classdef drEEMstatus
% Copyright (C) 2025 Urban J. Wuensch - wuensch@chalmers.se
% Chalmers University of Technology
% Department of Architecture and Civil Engineering
% Sven Hultins Gata 6
% 41296 Gothenburg (Sweden)
    properties (GetAccess = public,SetAccess = protected)
        spectralCorrection ...
            {mustBeText,...
            mustBeMember(spectralCorrection,...
            ["unknown","not applied","applied by instrument software","applied by toolbox"])} = "unknown"
        IFEcorrection ...
            {mustBeText,...
            mustBeMember(IFEcorrection,...
            ["unknown","not applied","applied by instrument software","applied by toolbox",...
            "deemed unnecessary"])} = "unknown"
        blankSubtraction ...
        {mustBeText,...
            mustBeMember(blankSubtraction,...
            ["unknown","not applied","applied by instrument software","applied by toolbox"])} = "unknown"
        signalCalibration ...
        {mustBeText,...
            mustBeMember(signalCalibration,...
            ["unknown","not applied","applied by instrument software (QSU)",...
             "applied by instrument software (RU)",...
             "applied by toolbox (RU)","applied by toolbox (QSU)"])} = "unknown"
        scatterTreatment ...
        {mustBeText,...
            mustBeMember(scatterTreatment,...
            ["unknown","not applied","applied by instrument software","applied by toolbox"])} = "unknown"
        signalScaling ...
             = "unknown"
        absorbanceUnit ...
            {mustBeText,...
            mustBeMember(absorbanceUnit,...
            ["unknown","absorbance per cm","absorbance per 5 cm","absorbance per 10 cm","Napierian absorption coefficient","Linear decadic absorption coefficient"])} = "unknown"
    end

    methods (Static=true)
        
        function obj = change(obj,prop,value)
            arguments
                obj {mustBeA(obj,"drEEMstatus")}
                prop ...
                    {mustBeMember(prop,...
                    ["spectralCorrection","IFEcorrection","blankSubtraction",...
                    "signalCalibration","scatterTreatment","signalScaling","absorbanceUnit"])}
                value {mustBeText}
            end

            obj.(prop)=value;

        end

        function outputArg = create(obj,inputArg)
            %METHOD1 Summary of this method goes here
            %   Detailed explanation goes here
            outputArg = obj.Property1 + inputArg;
        end
    end
end