function [helpdatabase] = retreivefileinfo
helpdatabase = {
    'dreem',            'doc_toolbox_product_page.html'
    'helpdoctest',         'f_template.html'
    'importeems',     'f_importeems.html'
    'importabsorbance','f_importabsorbance.html'
    'alignsamples',       'f_alignsamples.html'
    'randinitanal',     'f_randinitanal.html'
    'splitanalysis',    'f_splitanalysis.html'
    'splitvalidation',  'f_splitvalidation.html'
    'specsse',          'f_specsse.html'
    'loadingsandleverages','f_loadingsandleverages.html'
    'outliertest',      'f_outliertest.html'
    'smootheem',        'f_smootheem.html'
    'splitds',          'f_splitds.html'
    'zap',              'f_zap.html'
    'matchsamples',     'f_matchsamples.html'
    'alignds',          'f_alignds.html'
    'eemview',          'f_eemview.html'
    'eemreview',        'f_eemreview.html'
    'nwayparafac',      'f_nwayparafac.html'
    'describecomp',     'f_describecomp.html'
    'normeem',          'f_normeem.html'
    'scores2fmax',      'f_scores2fmax.html'
    'diffeem',          'f_diffeem.html'
    'spectralvariance', 'f_spectralvariance.html'
    'spectralloadings', 'f_spectralloadings.html'
    'fingerprint',      'f_fingerprint.html'
    'coreandvar',       'f_coreandvar.html'
    'errorsandleverages','f_errorsandleverages.html'
    'compcorrplot',     'f_compcorrplot.html'
    'compare2models',   'f_compare2models.html'
    'comparespectra',   'f_comparespectra.html'
    'pickpeaks',        'f_pickpeaks.html'
    'slopefit',         'f_slopefit.html'
    'ABAife',           'f_ABAife.html'
    'CDAife',           'f_CDAife.html'
    'fdomcorrect',      'f_fdomcorrect.html'
    'ramanintegrationrange','f_ramanintegrationrange.html'
    'undilute',         'f_undilute.html'
    'checkdataset',     'f_checkdataset.html'
    'scanview',         'f_scanview.html'
    'relcomporder',     'f_relcomporder.html'
    'handlescatter',    'f_handlescatter.html'
    'openfluormatches', 'f_openfluormatches.html'
    'modelexport',      'f_modelexport.html'
    'explorevariability','f_explorevariability.html'
    };
end